AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  AWSCostLINE

  Sample SAM Template for AWSCostLINE

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  AWSCostIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action: "sts:AssumeRole"
            Principal:
              Service: lambda.amazonaws.com
      Policies:
        - PolicyName: "AWSCostLambdaPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "ce:GetCostAndUsage"
                  - "ce:GetCostForecast"
                Resource: "*"
              - Effect: "Allow"
                Action:
                  - "secretsmanager:GetSecretValue"
                Resource: "arn:aws:secretsmanager:ap-northeast-1:141864838114:secret:LINE_CHANNEL_ACCESS_TOKEN-d0kHNM"
              - Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "*"
  AWSCostFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Role: !GetAtt AWSCostIAMRole.Arn
      CodeUri: aws_cost/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        AWSCost:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref AWSCostApi
            Path: /cost
            Method: post
  AWSCostApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: aws-cost-api
      StageName: v1
      OpenApiVersion: 3.0.3

Outputs:
  AWSCostApi:
    Description: "API Gateway endpoint URL for v1 stage for function"
    Value: !Sub "https://${AWSCostApi}.execute-api.${AWS::Region}.amazonaws.com/v1/cost/"
  AWSCostFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt AWSCostFunction.Arn
  AWSCostIAMRole:
    Description: "Implicit IAM Role created for function"
    Value: !GetAtt AWSCostIAMRole.Arn
